<a href="https://colab.research.google.com/github/reban87/ML-From-Scratch/blob/main/01%20Introduction_to_ML/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Introduction to NumPy

What will we cover?
- Creating arrays
- Multi diensional array
-Randomly generated arrays
- Element wise operations
  - Comparision operations
  - LOGICAL OPERATIONS
- Summarizing operations


### Single dimensional arrays

In [1]:
import numpy as np

Creating arrays



In [3]:
var = np.zeros(5)
print(type(var))

<class 'numpy.ndarray'>


In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.full(10, 3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [10]:
a = np.array([1, 2, 3, 4])
a[2] = 5
a

array([1, 2, 5, 4])

In [11]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

 Create arrays with evenly spaced numbers within a specified range


In [13]:
np.linspace(0, 100, 10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

### Multidimensional Arrays

In [14]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
# create an MD unit Array of size (5,2)
# Generate a random array of size (3, 5) with elements of your choice
# update the element of an array with index

In [16]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
n[0, 1] = 20
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [18]:
n[2] = [1, 1, 1]
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [19]:
n[:, 2] = [2, 2, 2]
n

array([[ 1, 20,  2],
       [ 4,  5,  2],
       [ 1,  1,  2]])

### Randomly generated arrays

- NumPy can create arrays filled with random numbers.
- To ensure the reproducibility, you can set a seed using np.random.seed()

- Everytime you run the code with np.random.seed(2), it will generate the exact same random numbers.

 If you remove or change the seed values, the sequence of random numbers will be changed

In [26]:
np.random.rand(5)

array([0.97243414, 0.80487641, 0.80976637, 0.76612017, 0.67575577])

In [44]:
np.random.seed(2)
np.random.rand(5)

array([0.4359949 , 0.02592623, 0.54966248, 0.43532239, 0.4203678 ])

In [59]:
np.random.seed(5)
np.random.rand(5, 2)

array([[0.22199317, 0.87073231],
       [0.20671916, 0.91861091],
       [0.48841119, 0.61174386],
       [0.76590786, 0.51841799],
       [0.2968005 , 0.18772123]])

In [60]:
np.random.randn(5, 2)

array([[ 0.18760323, -0.32986996],
       [-1.19276461, -0.20487651],
       [-0.35882895,  0.6034716 ],
       [-1.66478853, -0.70017904],
       [ 1.15139101,  1.85733101]])

In [61]:
np.random.seed(42)
np.random.randint(low=0, high=100, size=(5, 2))

array([[51, 92],
       [14, 71],
       [60, 20],
       [82, 86],
       [74, 74]])

### Element wise operations

In [62]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [63]:
b = (10 + (a*2))
b

array([10, 12, 14, 16, 18])

In [65]:
# Comparision operations
# You can perform element -wise comparisions and create boolean arrays
a

array([0, 1, 2, 3, 4])

In [66]:
a >= 2

array([False, False,  True,  True,  True])

In [67]:
a > b

array([False, False, False, False, False])

In [68]:
# Summarizing
# NumPy provides functions for summarizing array of data
a

array([0, 1, 2, 3, 4])

In [70]:
# standard deviation
a.std()

1.4142135623730951

In [72]:
# min value of an array
a.min()

0

In [73]:
# max value of an array
a.max()

4

In [74]:
# sum of the elements of an array
a.sum()

10